export const fakeMovies = [
  {
    Title: "Movie 1",
    Year: "2020",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 2",
    Year: "2021",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 3",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 4",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 5",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 6",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 7",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 8",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 9",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 10",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 11",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 12",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 13",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 14",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 15",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 16",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 17",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 18",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 19",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 20",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 21",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 22",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 23",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 24",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 25",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 26",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 27",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 28",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 29",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 30",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 31",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 32",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 33",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 34",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 35",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 36",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 37",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 38",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 39",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 40",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 41",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 42",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 43",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 44",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 45",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 46",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 47",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 48",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 49",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 50",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 51",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 52",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 53",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 54",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 55",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 56",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 57",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 58",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 59",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 60",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 61",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 62",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 63",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 64",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 65",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 66",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 67",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 68",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 69",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 70",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 71",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 72",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 73",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 74",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 75",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 76",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 77",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 78",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 79",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 80",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 81",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 82",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 83",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 84",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 85",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 86",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 87",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 88",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 89",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 90",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 91",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 92",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 93",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 94",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 95",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 96",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 97",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 98",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 99",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 100",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 101",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 102",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 103",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 104",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 105",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 106",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 107",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 108",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 109",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 110",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 111",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 112",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 113",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 114",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 115",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 116",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 117",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 118",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 119",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 120",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
  {
    Title: "Movie 121",
    Year: "2022",
    Poster: "https://via.placeholder.com/300x450",
    imdbID: "adgadg35",
    imdbRating: "2.5",
    Released: "27 july 2005",
    Genre: "Horror",
    Plot: "some plot",
  },
];
